assignment 3 first commit
spsparmar/Node_Assignments pull request #3
Opened 2017-06-12 08:07 UTC by spsparmar

2017-06-13 14:07 UTC, devanshutechracers commented on assignment3.yaml
> +- "http"
http!!!!

2017-06-13 14:10 UTC, devanshutechracers requested changes
Changes are required in the submission. I have made the comments on the Pull request about the changes

2017-06-13 15:01 UTC, devanshutechracers approved these changes

2017-06-13 15:09 UTC, rockon1985 requested changes
Check the version of the github API and update accordingly

2017-06-13 15:09 UTC, ketanTechracers commented on assignment3.yaml
> +  version: "1.0.0"
version 1?? Check the version of the github API and update accordingly!

2017-06-13 17:51 UTC, rockon1985 approved these changes

2017-06-13 18:33 UTC, merged

2017-06-19 14:16 UTC, devanshutechracers commented on assignment3.yaml
> +  version: "3"
should be "v3" not just 3

2017-06-19 14:16 UTC, devanshutechracers commented on assignment3.yaml
> +      - name: "order"
`description` property should be provided.

2017-06-19 14:17 UTC, devanshutechracers commented on assignment3.yaml
> +      - name: "sort"
`description` property should be provided.

2017-06-19 14:17 UTC, devanshutechracers commented on assignment3.yaml
> +      - name: "q"
`description` property should be provided.

2017-06-19 14:38 UTC, devanshutechracers commented on assignment3.yaml
> +definitions:
relevant examples are missing from definitions