assignment4 1st commit
spsparmar/Node_Assignments pull request #4
Opened 2017-06-13 14:07 UTC by spsparmar

2017-06-13 14:11 UTC, devanshutechracers commented on assignment4.js
> +readfile(0);
there is no readFile function.

2017-06-13 14:16 UTC, devanshutechracers requested changes
Runtime Error, 'No Such Function Exists'. :(

2017-06-13 15:14 UTC, devanshutechracers approved these changes

2017-06-13 15:22 UTC, rockon1985 requested changes
Make the mentioned code improvements

2017-06-13 15:22 UTC, ketanTechracers commented on assignment4.js
> +function myreadfile(index)	{
camelCase the function name

2017-06-13 15:22 UTC, ketanTechracers commented on assignment4.js
> +	if(index==fileArray.length) return;
Indentation Again!?

2017-06-13 15:22 UTC, ketanTechracers commented on assignment4.js
> +
remove this extra new line.

2017-06-13 15:22 UTC, ketanTechracers commented on assignment4.js
> +	fs.readFile(fileArray[index], 'utf8', function(error,data)	{
extra spaces/tab between function name and it's scope beginning.

2017-06-13 15:22 UTC, ketanTechracers commented on assignment4.js
> +	if(index==fileArray.length) return;
there should be a space before and after operator in JS code. `a + b` but not `a+b`

2017-06-13 15:22 UTC, ketanTechracers commented on assignment4.js
> +var fileArray= ['file1','file2','file3','file4','file5'];
- there should be a space before and after operator in JS code.`a + b` but not `a+b`
- there should be a space after comma after each array element.

2017-06-13 17:49 UTC, rockon1985 approved these changes

2017-06-13 17:53 UTC, devanshutechracers commented on assignment4.js
> +function myReadfile(index)  {
New lines required to improve readability.

2017-06-13 17:53 UTC, devanshutechracers commented on assignment4.js
> +console.log("============");
New lines required to improve readability.

2017-06-13 17:53 UTC, devanshutechracers commented on assignment4.js
> +console.log("============");
New lines required above and below console to improve readability.

2017-06-13 17:54 UTC, devanshutechracers requested changes
Readability should be improved,

2017-06-13 18:15 UTC, devanshutechracers approved these changes

2017-06-13 18:33 UTC, merged

2017-06-19 14:14 UTC, devanshutechracers commented on assignment4.js
> +  if(index == fileArray.length)
should use === instead of ==

2017-06-19 14:15 UTC, devanshutechracers commented on assignment4.js
> +    console.log(data);
What if there is an error occurred while Reading the file.

2017-06-20 12:14 UTC, devanshutechracers commented on assignment4.js
> +var fileArray= ['file1', 'file2', 'file3', 'file4', 'file5'];
space around `=` operator is required.